# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!


target 'gallery' do
pod 'pop', '~> 1.0.8'
pod 'Alamofire', '~> 3.0.0'
pod 'ObjectiveGumbo', '~> 0.1'
pod 'MBProgressHUD', '>= 0.9.1' # Objective-C pod
pod 'hpple', '~> 0.2.0'
pod 'AlamofireImage', '~> 2.0.0'
end

target 'galleryTests' do

end

target 'galleryUITests' do

end

